"""initial schema

Revision ID: c4efb69106f9
Revises: 
Create Date: 2026-06-09 06:46:07.144262
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4efb69106f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b24_type', sa.String(length=64), nullable=False),
    sa.Column('b24_id', sa.String(length=64), nullable=False),
    sa.Column('ms_type', sa.String(length=64), nullable=False),
    sa.Column('ms_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b24_type', 'b24_id', 'ms_type', 'ms_id', name='uq_entity_link')
    )
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.create_index('ix_entity_links_b24', ['b24_type', 'b24_id'], unique=False)
        batch_op.create_index('ix_entity_links_ms', ['ms_type', 'ms_id'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_operation_id'), ['operation_id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_operations_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_type'), ['type'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('entity_ref', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_operation_id'), ['operation_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_source'), ['source'], unique=False)

    op.create_table('workflow_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('dry_run_override', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_configs_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_configs_key'))

    op.drop_table('workflow_configs')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_source'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_processed'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_operation_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_type'))
        batch_op.drop_index(batch_op.f('ix_operations_status'))
        batch_op.drop_index(batch_op.f('ix_operations_source'))
        batch_op.drop_index(batch_op.f('ix_operations_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_operations_created_at'))

    op.drop_table('operations')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_operation_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_links_ms')
        batch_op.drop_index('ix_entity_links_b24')

    op.drop_table('entity_links')
    # ### end Alembic commands ###
