"""reference mappings

Revision ID: fb0f0950920e
Revises: c4efb69106f9
Create Date: 2026-06-09 09:59:59.411383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0f0950920e'
down_revision: Union[str, None] = 'c4efb69106f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('b24_value', sa.String(length=128), nullable=False),
    sa.Column('ms_type', sa.String(length=64), nullable=False),
    sa.Column('ms_id', sa.String(length=64), nullable=False),
    sa.Column('ms_name', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'b24_value', name='uq_reference_mapping')
    )
    with op.batch_alter_table('reference_mappings', schema=None) as batch_op:
        batch_op.create_index('ix_reference_mappings_kind', ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_reference_mappings_kind')

    op.drop_table('reference_mappings')
    # ### end Alembic commands ###
